# Generated by Django 4.2.13 on 2024-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='My Cart', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.CharField(default='details', max_length=255),
        ),
    ]
