# Generated by Django 4.2.13 on 2024-06-27 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_name_product_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inStock', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('retailPrice', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableForSale', models.BooleanField()),
                ('attributes', models.ManyToManyField(to='store.attribute')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.price'),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(to='store.variant'),
        ),
    ]
