# Generated by Django 4.2.13 on 2024-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_attribute_price_remove_product_display_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('total', models.IntegerField()),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='attributes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variants',
        ),
        migrations.AddField(
            model_name='product',
            name='available_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='display_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.AddField(
            model_name='order',
            name='products_in_order',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
