# Generated by Django 4.2.13 on 2024-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('why', models.CharField(max_length=255)),
                ('due_date', models.DateField(verbose_name='due date')),
                ('required', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
