# Generated by Django 4.2.13 on 2024-07-07 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='chore',
            name='created_date',
        ),
        migrations.AddField(
            model_name='chore',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chore',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='completed date'),
        ),
        migrations.AddField(
            model_name='chore',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('AV', 'Available'), ('CL', 'Claimed'), ('IP', 'Inprogress'), ('CO', 'Complete')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='chore',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='chore',
            name='why',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chores.chorelist'),
        ),
    ]
