# Generated by Django 4.2.13 on 2024-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('request_type', models.CharField(choices=[('ADD', 'Add'), ('SUB', 'Subtract')], default='ADD', max_length=3)),
                ('status', models.CharField(choices=[('P', 'Processing'), ('C', 'Complete')], default='P', max_length=1)),
                ('account_number', models.IntegerField()),
            ],
        ),
    ]
