# Generated by Django 4.2.13 on 2024-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='account_name',
            field=models.CharField(default='My Bank Account', max_length=50),
        ),
    ]
